version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: notely-backend
    command: node server.js
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/notely
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./backend:/app:cached

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notely-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev

volumes:
  mongo-data:
